<?php
/**
 * @namespace
 */
namespace de\imxnet\imxplatformphp\http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-29 at 21:25:20.
 */
class DefinitionsProviderTest extends \de\codenamephp\platform\test\TestCase {

  /**
   * @var DefinitionsProvider
   */
  private $sut = null;

  /**
   *
   * @var \de\codenamephp\platform\di\Container
   */
  private $di = null;

  protected function setUp() {
    $this->sut = new DefinitionsProvider();

    $containerBuilder = new \de\codenamephp\platform\di\ContainerBuilder();
    $containerBuilder->addDefinitionsByProvider($this->sut);
    $this->di = $containerBuilder->build();
  }

  public function testcanGetServerResponse_fromDiContainer() {
    self::assertInstanceOf(\Psr\Http\Message\ServerRequestInterface::class, $this->di->get(\Psr\Http\Message\ServerRequestInterface::class));
  }
}
